# kvhoeve
# 13/11/2023
# classes for CLIP

uk_landscape_weather_terms = [
    "Dramatic sky",
    "Sunset",
    "Sunrise",
    "Rainbow",
    "Stormy clouds",
    "Golden hour",
    "Misty morning",
    "Foggy landscape",
    "Snow-covered",
    "Glistening frost",
    "Clear blue sky",
    "Soft sunlight",
    "Rolling clouds",
    "Shadows",
    "Reflection",
    "Calm seas",
    "Rough seas",
    "Windswept",
    "Lush greenery",
    "Autumn colors",
    "Spring blossoms",
    "Summer haze",
    "Winter wonderland",
    "Sunbeams",
    "Hazy horizon",
    "Moody atmosphere",
    "Chasing storms",
    "Epic landscapes",
    "Serene countryside",
    "Coastal breeze"
]

uk_landscape_aesthetics_terms = [
    "Silhouette",
    "Blur",
    "Symmetry",
    "Leading lines",
    "Rule of thirds",
    "Depth of field",
    "Golden ratio",
    "Minimalism",
    "Texture",
    "Contrast",
    "Lighting",
    "Soft focus",
    "Vivid colors",
    "Dappled light",
    "Long exposure",
    "Panorama",
    "Moodiness",
    "Dramatic shadows",
    "Serene atmosphere",
    "Ethereal",
    "Pastel tones",
    "Vintage filter",
    "High dynamic range (HDR)",
    "Crisp details",
    "Breathtaking vistas",
    "Aerial perspective",
    "Urban decay",
    "Candid moments",
    "Timeless elegance",
    "Whimsical scenes"
]

uk_landscape_land_use_terms = [
    "Farmland",
    "Pasture",
    "Countryside",
    "Woodland",
    "Meadow",
    "Vineyard",
    "Orchard",
    "Village",
    "Hamlet",
    "English garden",
    "Country estate",
    "Pastoral",
    "Ruins",
    "Greenbelt",
    "Canal towpath",
    "Hiking trail",
    "National park",
    "Nature reserve",
    "Golf course",
    "Wind farm",
    "Solar farm",
    "Parkland",
    "Mine",
    "Rural road",
    "Railway tracks",
    "Historic site",
    "Brownfield",
    "Industrial estate",
    "Harbor",
    "Rural"
]

uk_landscape_structures_terms = [
    "Stone bridge",
    "Windmill",
    "Historic factory",
    "Aqueduct",
    "Castle ruins",
    "Stone circle",
    "Viaduct",
    "Farmhouse",
    "Fountain",
    "Church spire",
    "Canal lock",
    "Mill",
    "Boat house",
    "Old mill",
    "Stable",
    "Stone wall",
    "Thatched roof",
    "Arched bridge",
    "Historic mansion",
    "Water wheel",
    "Victorian architecture",
    "Statue",
    "Lock gate",
    "Cottage garden",
    "Stone archway",
    "Victorian bridge",
    "Weir",
    "Covered bridge",
    "Tudor-style building",
    "Walled garden"
]

uk_landscape_buildings_terms = [
    "Cottage",
    "Manor house",
    "Castle",
    "Church",
    "Cathedral",
    "Abbey",
    "Mansion",
    "Rectory",
    "Inn",
    "Pub",
    "Townhouse",
    "Terraced house",
    "Village hall",
    "School building",
    "University",
    "Library",
    "Museum",
    "Gallery",
    "Hospital",
    "Railway station",
    "Train shed",
    "Post office",
    "Town hall",
    "Courthouse",
    "Theatre",
    "Cinema",
    "Factory",
    "Town square",
    "Row of shops",
    "Bandstand"
]

uk_landscape_relief_terms = [
    "Escarpment",
    "Dale",
    "Drumlin",
    "Spur",
    "Vale",
    "Headland",
    "Inlet",
    "Firth",
    "Ria",
    "Moor",
    "Heath",
    "Tors",
    "Bluff",
    "Glen",
    "Wolds",
    "Quarry",
    "Mountain",
    "Graben",
    "Kame",
    "Upland",
    "Downland",
    "Corrie",
    "Col",
    "Mere",
    "Sinkhole",
    "Uvala",
    "Shoal",
    "Holm",
    "Ravine",
    "Ridge and furrow"
]

uk_landscape_water_bodies_terms = [
    "Brook",
    "Streamlet",
    "Rill",
    "Rivulet",
    "Tarn",
    "Beck",
    "Wash",
    "Backwater",
    "Leat",
    "Lough",
    "Sound",
    "Loch",
    "Fjord",
    "River",
    "Moorland pool",
    "Brackish lagoon",
    "Vernal pool",
    "Wet meadow",
    "Riparian zone",
    "Reeds",
    "Millpond",
    "Fishing pond",
    "Wildlife pond",
    "Marl lake",
    "Gravel pit",
    "Drainage ditch",
    "Tidal creek",
    "Floodplain",
    "Reflecting pool",
    "Mudflat"
]

uk_landscape_vegetation_terms = [
    "Bluebell wood",
    "Heathland",
    "Woods edge",
    "Fruit trees",
    "Hedgerow",
    "Thicket",
    "Moss", # XX
    "Beech grove",
    "Oak copse",
    "Gorse",
    "Coppice",
    "Peat Bog",
    "Marsh",
    "Fen",
    "Salt marsh",
    "Riverbank vegetation",
    "Estuarine vegetation",
    "Reedbed",
    "Coastal dunes",
    "Salt-tolerant flora",
    "Deciduous woodland",
    "Coniferous forest",
    "Moorland",
    "Mountain heath",
    "Lichen-covered rocks",
    "Fern",
    "Wildflower meadow",
    "Holly grove",
    "Cedar forest",
    "Thistle patch"
]

uk_landscape_transportation_terms = [
    "Double-decker bus",
    "London black cab",
    "Red telephone box",
    "Canal boat",
    "Narrowboat",
    "Horse-drawn carriage",
    "Vintage car",
    "Cyclist",
    "Pedestrian",
    "Tram",
    "Railway crossing",
    "Train",
    "London Underground",
    "Bicycle lane",
    "Motorway",
    "Roundabout",
    "Traffic jam",
    "Pedestrian bridge",
    "Ferry",
    "Rowboat",
    "Footpath",
    "Pedestrian zone",
    "Scooter",
    "Electric vehicle",
    "Bike rack",
    "Caravan",
    "Lorry",
    "Rural bus stop",
    "Bicycle",
    "Motorcycle"
]

uk_landscape_infrastructure_terms = [
    "Streetlamp",
    "Road junction",
    "Railway viaduct",
    "Water tower",
    "Signal box",
    "Level crossing",
    "Road bridge",
    "Footbridge",
    "Bollards",
    "Traffic lights",
    "Litter bin",
    "Bus stop",
    "Telephone box",
    "Electrical substation",
    "Wind turbine",
    "Water treatment plant",
    "Gasworks",
    "Sewage plant",
    "Electrical pylon",
    "Transmission lines",
    "Dams",
    "Reservoir",
    "Aquifer",
    "Ferry terminal",
    "Lighthouse",
    "Coastal defenses",
    "Sea wall",
    "Breakwater",
    "Pier",
    "Harbor crane"
]

all_terms = uk_landscape_weather_terms + uk_landscape_aesthetics_terms + uk_landscape_land_use_terms + uk_landscape_structures_terms + uk_landscape_buildings_terms + uk_landscape_relief_terms + uk_landscape_water_bodies_terms + uk_landscape_vegetation_terms + uk_landscape_transportation_terms + uk_landscape_infrastructure_terms